# These are supported funding model platforms
# below github sponsporship includes theme owner who is unrelated to your project
ko_fi: teamyayin
open_collective: # Replace with a single Open Collective username
custom: # Replace with a single custom sponsorship URL
